services:
  postgres:
    image: docker.io/postgres:16
    environment:
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
      POSTGRES_DB: ${DJANGO_DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/data-persist-postgres:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8081:80
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
